/* =========================================================
   NOOR BILLING PRO — Supabase connection config
   =========================================================
   This file is normally auto-generated by build.js during
   Vercel deployment using your Environment Variables.

   Running locally without Vercel? You can also paste your
   Supabase URL and anon key directly below instead.
   ========================================================= */

window.SUPABASE_URL = "YOUR_SUPABASE_PROJECT_URL";
window.SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY";
